services:
  picraft-raspberry:
    # 1) build locally
    build:
      context: .
      dockerfile: Dockerfile
    # 2) tag it (optional, but lets you push/pull to a registry later)
    image: stensel8/picraft-raspberry:latest

    container_name: picraft-raspberry
    ports:
      - "25565:25565"

    # mount your host folder into /mc-data in the container
    volumes:
      - ./mc-data:/mc-data
    environment:
      EULA: "true"
      # Uncomment to override the paper download if you ever need it:
      # JAR_URL: "${JAR_URL}"
      # JAR_HASH: "${JAR_HASH}"
      # JAR_NAME: "${JAR_NAME}"
    restart: unless-stopped